### ISSUE TITLE
process_credentials support with CDK

### ISSUE THREAD

**Issue by pahud** [pahud/gitpod-workspace#1]
**process_credentials** is working with JS SDK (**v2.775.0**) now

<img width="1219" alt="圖片" src="https://user-images.githubusercontent.com/278432/96730849-33111f80-13e9-11eb-91dd-69e8f32e0e70.png">

But still not supported in AWS CDK

<img width="1088" alt="圖片" src="https://user-images.githubusercontent.com/278432/96731222-97cc7a00-13e9-11eb-9a7e-0373b4d14bc8.png">

A workaround is using [aws-export-credentials](https://github.com/benkehoe/aws-export-credentials) to export credentials in the env vars, but might be a concern for paranoid people as it exposes the credentials in env vars.

A workaround is to generate `~/.aws/credentials` with [refresh_credentials.sh](https://github.com/pahud/gitpod-workspace/blob/main/utils/refresh_credentials.sh) .

I am leaving this issue open for discussion and tracking.

**Comment by benkehoe** [comment]
See workaround for CDK here: https://github.com/aws/aws-cdk/issues/5455#issuecomment-713643500

**Comment by pahud** [comment]
> See workaround for CDK here: [aws/aws-cdk#5455 (comment)](https://github.com/aws/aws-cdk/issues/5455#issuecomment-713643500)

I noticed the workaround is eventually to expose the credentials in env var from its `sso()` function, which I believe some people might avoid doing this for some security concern. Sometimes programs tend to dump all env vars for debug mode logging and this might be a security concern.

**Comment by hoegertn** [comment]
Should be done!?

**Comment by pahud** [comment]
> Should be done!?

Yes. And I personally prefer `aws-sso-credential-process` in Bash so I wrote one here

https://github.com/pahud/vscode/blob/main/.devcontainer/bin/aws-sso-credential-process

And the setup experience would be like

https://www.youtube.com/watch?v=lKWPvBalInY&t=759s

I will add the shell script into this template repo and update the README shortly.
