### ISSUE TITLE
Add bash completion

### ISSUE THREAD

**Issue by hoegertn** [pahud/gitpod-workspace#2]
What do you think about adding bash completion support to the image. It would make the life of the developer easier. Especially support for git completions

**Comment by pahud** [comment]
> What do you think about adding bash completion support to the image. It would make the life of the developer easier. Especially support for git completions

That would be amazing! Can you open a PR for me? Thanks.

**Comment by pahud** [comment]
#7

**Comment by pahud** [comment]
Looks like we should add the completion in `.gitpod.yml`

https://github.com/pahud/gitpod-workspace/blob/9741ea88ed635edb7a796d16f46ee19bf81b5b71/.gitpod.yml#L9
